// GENERATED by scripts/bake-bottle-maps.ts. Do not edit by hand.

export type BottleMeta = {
  slug: string;
  source: { w: number; h: number };
  trim: { x: number; y: number; w: number; h: number };
  shoulder: number;
  capShape: "cylinder" | "sphere";
  capTint: readonly [number, number, number];
};

export const BOTTLE_META: Record<string, BottleMeta> = {
  "reva": {
    "slug": "reva",
    "source": {
      "w": 2000,
      "h": 2000
    },
    "trim": {
      "x": 536,
      "y": 346,
      "w": 940,
      "h": 1334
    },
    "shoulder": 0.363,
    "capShape": "cylinder",
    "capTint": [
      0.506,
      0.509,
      0.513
    ]
  },
  "riven": {
    "slug": "riven",
    "source": {
      "w": 2000,
      "h": 2000
    },
    "trim": {
      "x": 536,
      "y": 345,
      "w": 940,
      "h": 1336
    },
    "shoulder": 0.363,
    "capShape": "cylinder",
    "capTint": [
      0.406,
      0.401,
      0.398
    ]
  },
  "maree": {
    "slug": "maree",
    "source": {
      "w": 2000,
      "h": 2000
    },
    "trim": {
      "x": 536,
      "y": 346,
      "w": 939,
      "h": 1334
    },
    "shoulder": 0.363,
    "capShape": "cylinder",
    "capTint": [
      0.442,
      0.378,
      0.276
    ]
  },
  "solea": {
    "slug": "solea",
    "source": {
      "w": 2000,
      "h": 2000
    },
    "trim": {
      "x": 543,
      "y": 301,
      "w": 921,
      "h": 1385
    },
    "shoulder": 0.386,
    "capShape": "sphere",
    "capTint": [
      0.531,
      0.533,
      0.541
    ]
  },
  "bond": {
    "slug": "bond",
    "source": {
      "w": 2000,
      "h": 2000
    },
    "trim": {
      "x": 539,
      "y": 301,
      "w": 932,
      "h": 1384
    },
    "shoulder": 0.384,
    "capShape": "sphere",
    "capTint": [
      0.14,
      0.138,
      0.138
    ]
  },
  "oudor": {
    "slug": "oudor",
    "source": {
      "w": 2000,
      "h": 2000
    },
    "trim": {
      "x": 532,
      "y": 301,
      "w": 930,
      "h": 1364
    },
    "shoulder": 0.376,
    "capShape": "sphere",
    "capTint": [
      0.548,
      0.471,
      0.305
    ]
  }
};
