// GENERATED by scripts/ingest-models.ts. Do not edit by hand.
// Every model listed here renders in 3D on the stage; anything missing keeps its fallback.

export type ModelEntry = {
  /** Public URL of the optimised GLB */
  file: string;
  /** Normalised bounds [width, height (=1), depth] */
  size: readonly [number, number, number];
  /** Degrees around Y so the model's front faces the camera */
  yaw: number;
};

export const BOTTLE_MODELS: Record<string, ModelEntry> = {};

export const NOTE_MODELS: Record<string, ModelEntry> = {};
