/**
 * Bakes relighting maps from the bottle cutouts so the WebGL stage can light the real
 * product photos with live shaders (see PLAN.md §2).
 *
 * For each public/images/bottles/{slug}.png it writes public/images/bottles/maps/:
 *   {slug}-color.webp   the photo trimmed to its alpha bounds (lossless crop, no resampling)
 *   {slug}-normal.webp  tangent-space normals (RGB = n * 0.5 + 0.5)
 *   {slug}-mask.webp    R = cap metal, G = glass, B = printed label, A = glass thickness
 * and src/components/stage/bottle-meta.ts with per-bottle layout data.
 *
 * Run: npm run assets:bottles
 */
import fs from "node:fs/promises";
import path from "node:path";
import { bakeBottle, type Meta } from "../src/server/catalog/bake";

const ROOT = path.resolve(__dirname, "..");
const DIR = path.join(ROOT, "public/images/bottles");
const OUT = path.join(DIR, "maps");
const SLUGS = ["reva", "riven", "maree", "solea", "bond", "oudor"] as const;

async function main() {
  await fs.mkdir(OUT, { recursive: true });
  const metas: Meta[] = [];
  for (const slug of SLUGS) {
    const baked = await bakeBottle(await fs.readFile(path.join(DIR, `${slug}.png`)), slug);
    const meta = baked.meta;
    await fs.writeFile(path.join(OUT, `${slug}-color.webp`), baked.color);
    await fs.writeFile(path.join(OUT, `${slug}-normal.webp`), baked.normal);
    await fs.writeFile(path.join(OUT, `${slug}-mask.webp`), baked.mask);
    metas.push(meta);
    console.log(
      slug,
      meta.capShape,
      `shoulder=${meta.shoulder}`,
      `trim=${meta.trim.w}x${meta.trim.h}`,
      `cap=${meta.capTint}`,
    );
  }
  const ts = `// GENERATED by scripts/bake-bottle-maps.ts. Do not edit by hand.

export type BottleMeta = {
  slug: string;
  source: { w: number; h: number };
  trim: { x: number; y: number; w: number; h: number };
  shoulder: number;
  capShape: "cylinder" | "sphere";
  capTint: readonly [number, number, number];
};

export const BOTTLE_META: Record<string, BottleMeta> = ${JSON.stringify(
    Object.fromEntries(metas.map((m) => [m.slug, m])),
    null,
    2,
  )};
`;
  await fs.mkdir(path.join(ROOT, "src/components/stage"), { recursive: true });
  await fs.writeFile(path.join(ROOT, "src/components/stage/bottle-meta.ts"), ts);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
